<a href="https://colab.research.google.com/github/Frhan21/Praktikum-Labdas-Program/blob/main/Penyelesaian_Modul_M6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np
import pandas as pd

In [34]:
n = 5
# Keadaan Awal benda A dalam Keadaan diam
va = np.zeros(n)
ta = np.zeros(n)
ma = np.zeros(n)
pa = np.zeros(n)
for i in range (n):
  ma[i] = 140.5

# Keadaan awal Benda B
mb = np.array([140.5,153,165.5,178,190.5])
tb = np.array(([0.173,0.176,0.176,0.186,0.157]))
vb = 3/tb
pb = mb*vb

# Keadaan Setelah tumbukan
t_a = np.array([0.185,0.180,0.173,0.177,0.149])
v_a = 3 / t_a
p_a = ma*v_a

# Keadaan benda B Setelah Tumbukan adalah Diam 
t_b = np.zeros(n)
v_b = np.zeros(n)
p_b = np.zeros(n)



data = {
    'mA' : ma,
    'tA' : ta,
    'pA' : pa,
    'mB' : mb,
    'tB' : tb,
    'vB' : vb,
    'pB' : pb,
    "t'A":t_a,
    "v'A":v_a,
    "p'A":p_a,
    "t'B":t_b,
    "v'B":v_b,
    "p'B":p_b,
}
print('='*90,'\n                        Tabel 1 Data Pengukuran Tumbukan elastis ')
print('-'*90)
pd.set_option('display.float_format', lambda x : f"{x:.3f}")
df = pd.DataFrame(data)
display(df)
if sum(pb) == sum(p_a):
  a =('Hukum Kekekalan Momentum Berlaku pada Bercobaan ini')
else :
  a =('Hukum Kekekalan Momentukm tidak Berlaku ')
print(f'''{"="*90}
Apakah Hukum Kekekalan Momentum berlaku pada percobaan ini ??
Jawabannya adalah {a}
P sebelum = P sesudah 
{sum(pa)+sum(pb):.3e} = {sum(p_a)+sum(p_b):.3e} Tidak sama antara kedua nilainya 
{"="*90}''')

==========================================================================================
                        Tabel 1 Data Pengukuran Tumbukan elastis
------------------------------------------------------------------------------------------

,mA,tA,pA,mB,tB,vB,pB,t'A,v'A,p'A,t'B,v'B,p'B
0,140.500,0.000,0.000,140.500,0.173,17.341,2436.416,0.185,16.216,2278.378,0.000,0.000,0.000
1,140.500,0.000,0.000,153.000,0.176,17.045,2607.955,0.180,16.667,2341.667,0.000,0.000,0.000
2,140.500,0.000,0.000,165.500,0.176,17.045,2821.023,0.173,17.341,2436.416,0.000,0.000,0.000
3,140.500,0.000,0.000,178.000,0.186,16.129,2870.968,0.177,16.949,2381.356,0.000,0.000,0.000
4,140.500,0.000,0.000,190.500,0.157,19.108,3640.127,0.149,20.134,2828.859,0.000,0.000,0.000

==========================================================================================
Apakah Hukum Kekekalan Momentum berlaku pada percobaan ini ??
Jawabannya adalah Hukum Kekekalan Momentukm tidak Berlaku
P sebelum = P sesudah
1.438e+04 = 1.227e+04 Tidak sama antara kedua nilainya
==========================================================================================

In [35]:
n = 5
# Keadaan Awal benda A dalam Keadaan diam
va = np.zeros(n)
ta = np.zeros(n)
ma = np.zeros(n)
pa = np.zeros(n)
for i in range (n):
  ma[i] = 140.5

# Keadaan awal Benda B
mb = np.array([140.5,153,165.5,178,190.5])
tb = np.array(([0.02244,0.03080,0.02479,0.03551,0.03675]))
vb = 3/tb
pb = mb*vb

# Keadaan Setelah tumbukan
t_ab = np.array([0.0974,0.238,0.0834,0.113,0.127])
v_ab = 3 / t_ab
p_ab = (ma+mb)*v_ab




data = {
    'mA' : ma,
    'tA' : ta,
    'pA' : pa,
    'mB' : mb,
    'tB' : tb,
    'vB' : vb,
    'pB' : pb,
    "t'AB":t_ab,
    "v'AB":v_ab,
    "p'AB":p_ab
}
print('='*90,'\n                      Tabel 1 Data Pengukuran Tumbukan Tidak Elastis ')
print('-'*90)
pd.set_option('display.float_format', lambda x : f"{x:.4f}")
df = pd.DataFrame(data)
display(df)
if sum(pb) == sum(p_ab):
  a =('Hukum Kekekalan Momentum Berlaku pada Bercobaan ini')
else :
  a =('Hukum Kekekalan Momentukm tidak Berlaku ')
print(f'''{"="*90}
Apakah Hukum Kekekalan Momentum berlaku pada percobaan ini ??
Jawabannya adalah {a}
P sebelum = P sesudah 
{sum(pa)+sum(pb):.3e} = {sum(p_ab):.3e} Tidak sama antara kedua nilainya 
{"="*90}''')

==========================================================================================
                      Tabel 1 Data Pengukuran Tumbukan Tidak Elastis
------------------------------------------------------------------------------------------

,mA,tA,pA,mB,tB,vB,pB,t'AB,v'AB,p'AB
0,140.5000,0.0000,0.0000,140.5000,0.0224,133.6898,18783.4225,0.0974,30.8008,8655.0308
1,140.5000,0.0000,0.0000,153.0000,0.0308,97.4026,14902.5974,0.2380,12.6050,3699.5798
2,140.5000,0.0000,0.0000,165.5000,0.0248,121.0165,20028.2372,0.0834,35.9712,11007.1942
3,140.5000,0.0000,0.0000,178.0000,0.0355,84.4832,15038.0175,0.1130,26.5487,8455.7522
4,140.5000,0.0000,0.0000,190.5000,0.0367,81.6327,15551.0204,0.1270,23.6220,7818.8976

==========================================================================================
Apakah Hukum Kekekalan Momentum berlaku pada percobaan ini ??
Jawabannya adalah Hukum Kekekalan Momentukm tidak Berlaku
P sebelum = P sesudah
8.430e+04 = 3.964e+04 Tidak sama antara kedua nilainya
==========================================================================================

In [53]:
# Bandingakan Nilai Energi Kinetik Sebelum dan Sesudah 
def Ek(p,v): 
  return 0.5 * p * v 

# Energi Kinetik Sebelum 
Ek1 = Ek(pb,vb)

# Energi Kinetik Sesudah 
Ek2 = Ek(p_ab,v_ab)

data = {
    'Energi Kinetik Sebelum ':Ek1,
    'Energi Kinetik Sesudah ':Ek2
}

pd.set_option('display.float_format', lambda x : f'{x:.3e}')
df = pd.DataFrame(data,index=[1,2,3,4,5])
display(df)
print(f'{"="*50}\nJumlah    {sum(Ek1):16.3e}{sum(Ek2):24.3e}')
print(f'''{"="*50}''')

   Energi Kinetik Sebelum   Energi Kinetik Sesudah
1                1.256e+06                1.333e+05
2                7.258e+05                2.332e+04
3                1.212e+06                1.980e+05
4                6.352e+05                1.122e+05
5                6.347e+05                9.235e+04

==================================================
Jumlah           4.463e+06               5.592e+05
==================================================